apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: external-nginx
  defaultBackend:
    service:
      name: first
      port:
        number: 80
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: first
                port:
                  number: 80
          - path: /second
            pathType: Prefix
            backend:
              service:
                name: second
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.domainNameSecretTLS }}
