apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: {{ .Values.namespace }}
spec:
  defaultBackend:
    service:
      name: first
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /first
            pathType: Prefix
            backend:
              service:
                name: first
                port:
                  number: 80
          - path: /second
            pathType: Prefix
            backend:
              service:
                name: second
                port:
                  number: 80
