apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: apps
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
      tolerations:
      - effect: NoSchedule
        operator: Exists