apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  # metadata.labels sets the labels that apply to the service.
  labels: 
    tier: php-fpm
spec:
  selector:
    app: php-fpm
  ports:
  - name: php-fpm
    protocol: TCP
    port: 9000