apiVersion: apps/v1
kind: Deployment
metadata:
  name: third
  namespace: apps
  labels:
    app.kubernetes.io/name: third
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: third
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: third
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: third
          image: hashicorp/http-echo
          imagePullPolicy: IfNotPresent
          args:
            - -listen=:3000
            - -text=third
          ports:
            - name: app-port
              containerPort: 3000
          resources:
            requests:
              cpu: 0.125
              memory: 50Mi
      tolerations:
        - key: role
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: third
  namespace: apps
  labels:
    app.kubernetes.io/name: third
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: third
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP