apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: myns
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 'nginx:1.24'
          imagePullPolicy: Always
          ports:
          - name: web
            containerPort: 80          
          volumeMounts:
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
      restartPolicy: Always
  strategy:
   type: RollingUpdate