apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: my-ns
data:
  default.conf: |
    server {
      index index.php;

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
      #
      location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME /var/www/index.php;
        include fastcgi_params;
      }

      location ~ \.php$ {
        return 404;
      }
    }